### PR TITLE
Fix vertical navigation active state for usage and accessibility tabs

### LINKED ISSUE #5678: Add scrolling to the active navigation item on site
### Description

On site, vertical navigation should scroll to active item on page load so users can see which nav item is open

### Expected behavior

When active nav item is not in view, the vertical nav should scroll to active nav link/item

### Alternatives and examples

.

### Context

Previous ticket: https://github.com/jpmorganchase/salt-ds/issues/5562#issuecomment-3408178938
Context on the issue: https://github.com/jpmorganchase/salt-ds/pull/5586#issuecomment-3328739822

### Are you a JPMorgan Chase & Co. employee?

- [x] I am an employee of JPMorgan Chase & Co.

### LINKED ISSUE #6074: Vertical navigation is only active on examples
### Related page(s)

https://www.saltdesignsystem.com/salt/components/accordion/usage

### Kind of issue

Other

### Description

Vertical navigation should stay active for a components doc, when in the examples, usage and accessibility tabs

### Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [x] I am an employee of JPMorgan Chase & Co.

### PR DESCRIPTION
**Pull request by wemmyo**
Closes #6074
Fixes the vertical navigation not highlighting the active tab when navigating to /usage, /accessibility routes and improve active nav item discoverability on site.

- Extends the route normalization function to include /usage, /accessibility, and /examples paths
- Ensures the vertical navigation correctly reflects the active state for these routes
- Auto scroll to active nav item only on initial load. Closes #5678

### CODE REVIEW

File: site/src/components/navigation/vertical-navigation/VerticalNavigation.tsx [hunk 1]
```diff
@@ -122,12 +122,37 @@ export const VerticalNavigation = ({
...
+    if (!navigationContainer) return;
+
+    const activeItem = navigationContainer.querySelector(
+      '[aria-current="page"]',
+    );
+    if (activeItem instanceof HTMLElement) {
+      activeItem.scrollIntoView({ block: "center" });
+      hasScrolledToActiveRef.current = true;
+    }
+  }, [mappedNavData, normalizedSelectedNodeId]);
```
Comment (tycup) [inline site/src/components/navigation/vertical-navigation/VerticalNavigation.tsx]: Does `mappedNavData` need to be in the dependancy array - i think its created fresh on each render via `mapMenu(menu)`?. I see its guarded by `hasScrolledToActiveRef `which makes it work but a bit misleading perhaps. 

Worth memoizing mappedNavData?

File: site/src/components/navigation/vertical-navigation/utils/index.ts
Comment (tycup) [inline site/src/components/navigation/vertical-navigation/utils/index.ts]: Does this comment need to be updated to include the routes added?

File: site/src/components/navigation/vertical-navigation/utils/index.ts [hunk 2]
```diff
@@ -23,8 +23,10 @@ export function statusToBadgeValue(status: string) {
  This function normalizes the selectedNodeId to match the href in navData
  **/
 export function normalizeSelectedNodeId(link: string, navData: Item[]): string {
```
Comment (tycup) [inline site/src/components/navigation/vertical-navigation/utils/index.ts:27]: nit - do you need regex here? `endsWith` already confirms the suffix so could use `slice` to remove it once instead of creating two RegExp objects

```
const base = link.slice(0, -matchedRoute.length);
const indexLink = `${base}/index`;
```

Comment (wemmyo) [reply site/src/components/navigation/vertical-navigation/utils/index.ts:27]: Good point thanks. Updated

File: site/src/components/navigation/vertical-navigation/utils/index.ts
Comment (wemmyo) [reply site/src/components/navigation/vertical-navigation/utils/index.ts]: Technically its still the case because /index will redirect to /examples by default but I've rewritten the comment to explain what the function does

File: site/src/components/navigation/vertical-navigation/VerticalNavigation.tsx (hunk 1 above)
Comment (wemmyo) [reply site/src/components/navigation/vertical-navigation/VerticalNavigation.tsx]: Yeah `mappedNavData` isn't a necessary dependency and has been removed. Thanks
