### PR TITLE
Typescript clean up

### LINKED ISSUE #3831: Facing Type Error in @Salt/lab 1.0.0-alpha.49 - Generic type 'ElementType' requires between 0 and 1 type arguments
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

@Salt/lab 1.0.0-alpha.49

### Description

[build:*types] > build:types
[build:*types] > tsc
[build:*types]
[build:*types] C:/JPMC/DEV/TMP/MSPayments/dsp-merchant-dashboard-mfe/node_modules/@internationalized/date/dist/types.d.ts(152,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
[build:*types] C:/JPMC/DEV/TMP/MSPayments/dsp-merchant-dashboard-mfe/node_modules/@internationalized/date/dist/types.d.ts(193,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
[build:*types] C:/JPMC/DEV/TMP/MSPayments/dsp-merchant-dashboard-mfe/node_modules/@internationalized/date/dist/types.d.ts(223,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
[build:*types] C:/JPMC/DEV/TMP/MSPayments/dsp-merchant-dashboard-mfe/node_modules/@internationalized/date/dist/types.d.ts(272,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
[build:*types] C:/JPMC/DEV/TMP/MSPayments/dsp-merchant-dashboard-mfe/node_modules/@salt-ds/lab/dist-types/form-field-legacy/FormHelperText.d.ts(7,49): error TS2707: Generic type 'ElementType' requires between 0 and 1 type arguments.
[build:*types] npm run build:types exited with code 2

### Steps to reproduce

Execute tsc command.
Using below versions:
npm 10.5.2
node js - 20.13.1
"@salt-ds/core": "^1.32.0",
    "@salt-ds/icons": "^1.12.1",
    "@salt-ds/lab": "^1.0.0-alpha.49",
    "@salt-ds/theme": "^1.20.0",

### Expected behavior

Expected to run build without errors.

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

### PR DESCRIPTION
**Pull request by joshwooding**
A small clean up to avoid referencing `React.*`. Cleaned up the legacy form helper text types in lab. Should close #3831

### CODE REVIEW

File: packages/lab/src/form-field-legacy/FormHelperText.tsx [hunk 1]
```diff
@@ -6,17 +6,16 @@ import { useWindow } from "@salt-ds/window";
 
 import formHelperTextCss from "./FormHelperText.css";
 
-export type FormHelperTextProps<E extends React.ElementType = "p"> =
-  ComponentPropsWithoutRef<E> & {
-    helperText: FormFieldProps["helperText"];
-    helperTextPlacement: FormFieldProps["helperTextPlacement"];
-  };
+export interface FormHelperTextProps extends ComponentPropsWithoutRef<"p"> {
```
Comment (joshwooding) [inline packages/lab/src/form-field-legacy/FormHelperText.tsx:9]: This component isn't polymorphic

**Review by libertymayc — APPROVED** [review]

**Review by mark-tate — APPROVED** [review]
