### PR TITLE
Fix ListBox ghost option selection bug

### LINKED ISSUE #5323: In a Salt list box, when attempting to select items a ghost selection shows briefly
### Latest version

- [x] I have tested the latest version

### Description

In a Salt list box, when attempting to select items a ghost selection shows briefly

### Steps to reproduce

.

### Expected behavior

_No response_

### Package name(s)

Core (@salt-ds/core)

### Package version(s)

_No response_

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

### PR DESCRIPTION
**Pull request by tayyabataimur**
Closes #5323

### CODE REVIEW

File: packages/core/src/option/Option.tsx [hunk 1]
```diff
@@ -88,6 +89,10 @@ export const Option = forwardRef<HTMLDivElement, OptionProps>(
         return;
       }
 
+      if (listRef && listRef.current) {
+        listRef.current.focus({ preventScroll: true });
+      }
+
```
Comment (joshwooding) [inline packages/core/src/option/Option.tsx]:
```suggestion
      listRef?.current?.focus({ preventScroll: true });
```

**Review by joshwooding — APPROVED** [review]

**Review by dplsek — APPROVED** [review]
