### PR TITLE
Fix Switch label alignment

### LINKED ISSUE #2372: Switch label vertical alignment
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

[@salt-ds/lab@1.0.0-alpha.16](https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Flab%401.0.0-alpha.16)

### Description

Switch is not vertically alignment to the center, should be spacing-25 from the top

### Steps to reproduce

https://storybook.saltdesignsystem.com/?path=/story/lab-switch-qa--all-examples-grid

### Expected behavior

Label vertically aligned

### Operating system

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

### PR DESCRIPTION
**Pull request by lukeac123**
Fixes #2372
Had to wrap the label in a new span so it could be styles independently to the whole component

### CODE REVIEW

File: packages/lab/src/switch/Switch.tsx [hunk 1]
```diff
@@ -89,7 +89,6 @@ export const Switch = forwardRef<HTMLLabelElement, SwitchProps>(function Switch(
   const {
     checked: checkedProp,
     className,
-    color,
```
Comment (lukeac123) [inline packages/lab/src/switch/Switch.tsx:92]: not being used anywhere - removing for now

File: .changeset/slow-pants-work.md [hunk 2]
```diff
@@ -0,0 +1,7 @@
+---
+"@salt-ds/core": patch
+"@salt-ds/lab": patch
+---
+
+Prevent DropDown and ComboBox rendering behind Dialog by increasing zIndex
```
Comment (origami-z) [inline .changeset/slow-pants-work.md:6]: this is in a separate PR?

File: .changeset/slow-pants-work.md [hunk 3]
```diff
@@ -0,0 +1,7 @@
+---
+"@salt-ds/core": patch
```
Comment (origami-z) [inline .changeset/slow-pants-work.md:2]: Let's split to 2 changeset file. One for core one for lab (when content is different for / irrelevant between each packages)

File: packages/core/src/checkbox/Checkbox.css [hunk 4]
```diff
@@ -4,6 +4,7 @@
   gap: var(--salt-spacing-100);
   position: relative;
   cursor: var(--salt-selectable-cursor-hover);
+  align-items: center;
```
Comment (origami-z) [inline packages/core/src/checkbox/Checkbox.css:7]: Check with design, i think the fix is to put spacing on top to accommodate multi-line label use cases. i.e. the box should be alined with first line of text only

Comment (origami-z) [reply packages/core/src/checkbox/Checkbox.css:7]: maybe also add multi-line use cases to Chromatic snapshot

**Comment by origami-z** [comment]
@jpmorganchase/salt-design needs design review on Chromatic

**Comment by origami-z** [comment]
Can we have one example of single line in Chromatic, and ask designer to check?

File: .changeset/slow-pants-work.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"@salt-ds/lab": patch
+---
+
+Centralise label alignment for Switch + Radio Button
```
Comment (alycrys) [inline .changeset/slow-pants-work.md:5]: radio button is in core

File: packages/core/src/checkbox/Checkbox.css [hunk 6]
```diff
@@ -18,6 +18,10 @@
   cursor: var(--salt-selectable-cursor-readonly);
 }
 
+.saltSwitch-label {
+  padding-top: var(--salt-spacing-25);
+}
```
Comment (alycrys) [inline packages/core/src/checkbox/Checkbox.css:23]: is this Switch styling necessary here?

File: packages/core/src/checkbox/Checkbox.tsx [hunk 7]
```diff
@@ -213,7 +213,7 @@ export const Checkbox = forwardRef<HTMLLabelElement, CheckboxProps>(
           validationStatus={validationStatus}
           error={error}
         />
-        {label}
+        <span className={withBaseName("label")}>{label}</span>
```
Comment (alycrys) [inline packages/core/src/checkbox/Checkbox.tsx:216]: this might not be necessary, don't think this class was used

File: packages/core/src/radio-button/RadioButton.css [hunk 8]
```diff
@@ -32,6 +32,10 @@
   z-index: var(--salt-zIndex-default);
 }
 
+.saltSwitch-label {
+  padding-top: var(--salt-spacing-25);
+}
+
```
Comment (alycrys) [inline packages/core/src/radio-button/RadioButton.css:38]: same as above

File: packages/core/src/radio-button/RadioButton.tsx [hunk 9]
```diff
@@ -198,7 +198,7 @@ export const RadioButton = forwardRef<HTMLLabelElement, RadioButtonProps>(
           validationStatus={validationStatus}
           error={error}
         />
-        {label}
+        <span className={withBaseName("label")}>{label}</span>
```
Comment (alycrys) [inline packages/core/src/radio-button/RadioButton.tsx:201]: same as above

File: packages/core/stories/checkbox/checkbox.stories.tsx [hunk 10]
```diff
@@ -248,17 +248,6 @@ export const LongTextGroup: StoryFn<typeof CheckboxGroup> = (args) => {
...
-      label:
-        "Radio buttons allow the user to select one option from a set. Use radio buttons for exclusive selection if you think that the user needs to see all available options side-by-side. Radio buttons allow the user to select one option from a set. Use radio buttons for exclusive selection if you think that the user needs to see all available options side-by-side.",
-      value: "radio",
-    },
-    {
-      disabled: true,
-      label:
-        "On/off switches toggle the state of a single settings option. The option that the switch controls, as well as the state it’s in, should be made clear from the corresponding inline label. Switch can also be used with a label description thanks to the FormControlLabel component.",
-      value: "switches",
-    },
```
Comment (alycrys) [inline packages/core/stories/checkbox/checkbox.stories.tsx:261]: is this supposed to be a group with only one checkbox? was there a reason for removing these?

File: packages/core/stories/radio-button/radio-button.stories.tsx [hunk 11]
```diff
@@ -144,19 +144,10 @@ export const ControlledGroup: StoryFn<typeof RadioButtonGroup> = ({
...
-      />
       <RadioButton
         label="Radio buttons allow the user to select one option from a set. Use radio buttons for exclusive selection if you think that the user needs to see all available options side-by-side. Radio buttons allow the user to select one option from a set. Use radio buttons for exclusive selection if you think that the user needs to see all available options side-by-side."
         value="radio"
       />
-      <RadioButton
-        label="On/off switches toggle the state of a single settings option. The option that the switch controls, as well as the state it’s in, should be made clear from the corresponding inline label. Switch can also be used with a label description thanks to the FormControlLabel component."
-        value="switches"
-        disabled
-      />
```
Comment (alycrys) [inline packages/core/stories/radio-button/radio-button.stories.tsx:159]: same as per checkbox story

File: packages/core/src/checkbox/Checkbox.css (hunk 6 above)
Comment (lukeac123) [reply packages/core/src/checkbox/Checkbox.css:23]: the styling is to center the text with the switch - https://github.com/jpmorganchase/salt-ds/issues/2372

File: packages/core/stories/checkbox/checkbox.stories.tsx (hunk 10 above)
Comment (lukeac123) [reply packages/core/stories/checkbox/checkbox.stories.tsx:261]: you're right doesn't make sense to have a group with only a single component - have added back

File: packages/core/src/checkbox/Checkbox.tsx (hunk 7 above)
Comment (lukeac123) [reply packages/core/src/checkbox/Checkbox.tsx:216]: not sure i understand - this is for the styling i've added for the label ?

File: packages/core/src/radio-button/RadioButton.css [hunk 12]
```diff
@@ -32,6 +32,10 @@
   z-index: var(--salt-zIndex-default);
 }
 
+.saltSwitch-label {
```
Comment (joshwooding) [inline packages/core/src/radio-button/RadioButton.css:35]:
```suggestion
.saltRadioButton-label {
```

File: packages/core/src/checkbox/Checkbox.css [hunk 13]
```diff
@@ -18,6 +18,10 @@
   cursor: var(--salt-selectable-cursor-readonly);
 }
 
+.saltSwitch-label {
```
Comment (joshwooding) [inline packages/core/src/checkbox/Checkbox.css:21]:
```suggestion
.saltCheckbox-label {
```

File: .changeset/thick-beds-kiss.md [hunk 14]
```diff
@@ -0,0 +1,5 @@
+---
+"@salt-ds/core": patch
+---
+
+Centralise label alignment for Checkbox + Radio Button
```
Comment (joshwooding) [inline .changeset/thick-beds-kiss.md:5]:
```suggestion
Fixed label alignment for Checkbox and Radio Button
```

File: .changeset/slow-pants-work.md [hunk 15]
```diff
@@ -0,0 +1,5 @@
+---
+"@salt-ds/lab": patch
+---
+
+Centralise label alignment for Switch
```
Comment (joshwooding) [inline .changeset/slow-pants-work.md:5]:
```suggestion
Fixed label alignment for Switch
```

**Review by joshwooding — CHANGES_REQUESTED** [review]
There seemed to be a lot of copy-and-paste errors here, doing a second review in GitHub might help catch these.

**Review by joshwooding — COMMENTED** [review]
Checkbox and Radio Button are off by 1px. Does this PR solve that?

**Comment by lukeac123** [comment]
Have reverted the changes for RadioButton and Checkbox - was seeing this misalignment in another repo using Salt but this was due to a conflict in the salt-ds/core dependency being used

**Review by joshwooding — APPROVED** [review]

**Review by joshwooding — CHANGES_REQUESTED** [review]
The QA example ended up a bit weird, with the new additions so it's harder to tell visual regressions, could we make the QA look closer?

**Review by joshwooding — APPROVED** [review]

**Review by Fercas123 — APPROVED** [review]
