### PR TITLE
Fix the icon inside Navigation Item having the incorrect color when a  parent item is also a link

### LINKED ISSUE #4023: Navigation Item's icon goes blue when the navigation item is a link
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

latest

### Description

image

### Steps to reproduce

https://storybook.saltdesignsystem.com/?path=/story/core-navigation-item--vertical-nested-group

### Expected behavior

_No response_

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

### PR DESCRIPTION
**Pull request by joshwooding**
Closes #4023

I decided to fix this two different ways:

- Fix the styling issue (icon taking the link styling)
- Update the docs to show our preferred usage of NavigationItem

### CODE REVIEW

File: .storybook/main.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ const config: StorybookConfig = {
   stories: ["../packages/*/stories/**/*.@(mdx|stories.@(js|jsx|ts|tsx))"],
   staticDirs: ["../docs/public"],
   typescript: {
-    reactDocgen: "react-docgen-typescript",
+    reactDocgen: false,
```
Comment (origami-z) [inline .storybook/main.ts:16]: what's wrong..? sb controls will not work?

Comment (joshwooding) [inline .storybook/main.ts:16]:
```suggestion
    reactDocgen: "react-docgen-typescript",
```

**Review by mark-tate — APPROVED** [review]

**Review by bhoppers2008 — APPROVED** [review]

**Review by dplsek — APPROVED** [review]
