### PR TITLE
Calendar fix default focus and out of range colors

### LINKED ISSUE #3340: Calendar selecting wrong day on keyboard nav
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

_No response_

### Description

keyboard navigation takes you to the first day, even when there is a selected day. order of priority should be: 
- selected
- today if the cal is in current month
- 1rst day

### Steps to reproduce

any calendar example

### Expected behavior

_No response_

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

### PR DESCRIPTION
**Pull request by Fercas123**
fixes #3340 & #3341 (date navigation and today's characteristic)

### CODE REVIEW

File: packages/lab/src/calendar/useCalendar.ts [hunk 1]
```diff
@@ -135,7 +135,7 @@ export function useCalendar(props: useCalendarProps) {
   const [calendarFocused, setCalendarFocused] = useState(false);
 
   const [focusedDate, setFocusedDateState] = useState<DateValue>(
-    startOfMonth(visibleMonth)
+    (selectedDate as DateValue) ?? today ?? startOfMonth(visibleMonth)
```
Comment (origami-z) [inline packages/lab/src/calendar/useCalendar.ts:138]: minor thing, logic here suggests today is also a preference, but not covered in test?

File: packages/lab/src/__tests__/__e2e__/calendar/Calendar.cy.tsx [hunk 2]
```diff
@@ -137,6 +137,36 @@ describe("GIVEN a Calendar", () => {
...
+        );
+        cy.findByRole("button", {
+          name: `Next Month, ${formatDate(testDate.add({ months: 1 }))}`,
+        }).focus();
+        cy.realPress("Tab");
+        cy.findByRole("button", {
+          name: formatDate(testDate),
+        }).should("be.focused");
+      });
+      it.only("SHOULD when there is no selected date, move from navigation panel to today if exists", () => {
```
Comment (joshwooding) [inline packages/lab/src/__tests__/__e2e__/calendar/Calendar.cy.tsx:152]:
```suggestion
      it("SHOULD when there is no selected date, move from navigation panel to today if exists", () => {
```

File: packages/lab/src/calendar/internal/CalendarDay.css [hunk 3]
```diff
@@ -29,7 +29,13 @@
 .saltCalendarDay-outOfRange {
   color: var(--salt-content-secondary-foreground);
 }
+.saltCalendarDay-outOfRange .saltCalendarDay-today {
+  border-bottom: var(--salt-size-indicator) var(--salt-selectable-borderStyle) var(--salt-content-secondary-foreground);
+}
 
+.saltCalendarDay-outOfRange .saltCalendarDay-highlighted {
```
Comment (joshwooding) [inline packages/lab/src/calendar/internal/CalendarDay.css:36]: I might be mistaken but this doesn't work? the outOfRange class and highlighted class are on the same element.

Comment (Fercas123) [inline packages/lab/src/calendar/internal/CalendarDay.css:36]:
```suggestion
.saltCalendarDay-outOfRange.saltCalendarDay-highlighted {
```

File: packages/lab/src/calendar/useCalendar.ts (hunk 1 above)
Comment (joshwooding) [reply packages/lab/src/calendar/useCalendar.ts:138]: Is this logic right? 

- We are using the controlled selectedDate which would stop this working if it was an uncontrolled calendar.
- `today` is the function to be called from internationalized which will never be undefined. This currently works because react calls it due to the lazy useState initialisation.
- startOfMonth will never be called because today is always valid.

There are now a lot of cases that need to be tested:
- Default, Selected dates receive initial focus
- Once navigating, the start of the month will always receive the initial focus
- If the visibleMonth does not contain today or selected date the first date receives focus (this is only happening right now due to the useEffect below)

**Review by joshwooding — DISMISSED** [review]

File: packages/lab/src/calendar/useCalendar.ts (hunk 1 above)
Comment (ivan-calderon) [reply packages/lab/src/calendar/useCalendar.ts]: @Fercas123 if useful, the [highlighted dates](https://113582bd.saltdesignsystem-storybook.pages.dev/?path=/story/lab-calendar--highlighted-dates) example is having styling issues when the highlight is in different month. .

**Comment by ivan-calderon** [comment]
@Fercas123 if useful, the [highlighted dates](https://113582bd.saltdesignsystem-storybook.pages.dev/?path=/story/lab-calendar--highlighted-dates) example is having styling issues when the highlight is in different month. .

File: packages/lab/src/calendar/internal/CalendarDay.css [hunk 4]
```diff
@@ -29,7 +29,13 @@
 .saltCalendarDay-outOfRange {
   color: var(--salt-content-secondary-foreground);
 }
+.saltCalendarDay-outOfRange .saltCalendarDay-today {
+  border-bottom: var(--salt-size-indicator) var(--salt-selectable-borderStyle) var(--salt-content-secondary-foreground);
+}
 
+.saltCalendarDay-outOfRange.saltCalendarDay-highlighted {
```
Comment (joshwooding) [inline packages/lab/src/calendar/internal/CalendarDay.css:36]:
```suggestion
.saltCalendarDay-outOfRange.saltCalendarDay-highlighted:before {
```

**Comment by joshwooding** [comment]
> @Fercas123 if useful, the [highlighted dates](https://113582bd.saltdesignsystem-storybook.pages.dev/?path=/story/lab-calendar--highlighted-dates) example is having styling issues when the highlight is in different month. .

I've suggested a fix for this. Also it looks like the different month hover text colour is wrong and is secondary should it be primary on hover to meet colour contrast?

File: packages/lab/src/calendar/useCalendar.ts [hunk 5]
```diff
@@ -134,8 +135,24 @@ export function useCalendar(props: useCalendarProps) {
 
   const [calendarFocused, setCalendarFocused] = useState(false);
 
+  const getInitialFocusedDate: () => DateValue | undefined = () => {
+    switch (selectionVariant) {
+      case "multiselect":
+        return defaultSelectedDate?.[0];
```
Comment (joshwooding) [inline packages/lab/src/calendar/useCalendar.ts:141]: This now will only work for uncontrolled and not controlled

File: packages/lab/src/__tests__/__e2e__/calendar/Calendar.cy.tsx [hunk 6]
```diff
@@ -137,6 +137,59 @@ describe("GIVEN a Calendar", () => {
     });
 
     describe("Keyboard", () => {
+      it("SHOULD move from navigation panel to selected date if exists", () => {
+        cy.mount(
+          <Default selectedDate={testDate} defaultVisibleMonth={testDate} />
```
Comment (joshwooding) [inline packages/lab/src/__tests__/__e2e__/calendar/Calendar.cy.tsx:142]: This test is passing but I'm not sure it should

**Review by joshwooding — APPROVED** [review]

**Review by lilyvc — APPROVED** [review]
