### PR TITLE
Fix Dialog background scroll

### LINKED ISSUE #3906: Disable background scroll when Dialog open
### Area

UI Components

### The problem

The current behavior of the Dialog component allows for background scrolling when the Dialog is open. This can sometimes lead to unintentionally scrolling the background content while interacting with the Dialog. It would be nice to have an option to disable this. 

### The solution

Add a new prop to Dialog which disables background scrolling. eg `disableBackgroundScrolling: boolean`

### Alternatives and examples

.

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

### PR DESCRIPTION
**Pull request by liamsms**
Closes #3906

Added `disableScroll` prop to FloatingComponent, which sets the document body overflow to `hidden` to prevent background scrolling.

### CODE REVIEW

**Comment by liamsms** [comment]
May require additional testing on a Mac due to potential differences in scroll behavior, eg. shifts in positioning when the scrollbar appears/disappears.

**Comment by Fercas123** [comment]
this change should probably be built as a prop in `FloatingComponent` rather than in dialog, since it could be reused in other implementations like drawer

File: packages/core/src/utils/useFloatingUI/useFloatingUI.tsx [hunk 1]
```diff
@@ -71,6 +77,20 @@ const DefaultFloatingComponent = forwardRef<
 
   const ChosenSaltProvider = themeNext ? SaltProviderNext : SaltProvider;
 
+  useEffect(() => {
+    if (!disableScroll) {
+      return;
+    }
+    if (open) {
+      document.documentElement.style.overflow = "hidden";
```
Comment (Fercas123) [inline packages/core/src/utils/useFloatingUI/useFloatingUI.tsx:85]: we should probably use `targetWindow`

Comment (liamsms) [reply packages/core/src/utils/useFloatingUI/useFloatingUI.tsx]: Hi - I've updated it to use `targetWindow`.

**Review by Fercas123 — APPROVED** [review]

**Review by tayyabataimur — APPROVED** [review]

**Review by joshwooding — CHANGES_REQUESTED** [review]
Will follow up with feedback

File: packages/core/src/utils/useFloatingUI/useFloatingUI.tsx [hunk 2]
```diff
@@ -45,6 +46,10 @@ export interface FloatingComponentProps
   width?: number;
   height?: number;
   position?: Strategy;
+  /**
+   * Disables scrolling the document body while the floating component is open.
+   */
+  disableScroll?: boolean;
```
Comment (joshwooding) [inline packages/core/src/utils/useFloatingUI/useFloatingUI.tsx:52]: We should check if we're happy with the naming here

Comment (mark-tate) [reply packages/core/src/utils/useFloatingUI/useFloatingUI.tsx:52]: What about 
https://floating-ui.com/docs/floatingoverlay#lockscroll

Comment (joshwooding) [reply packages/core/src/utils/useFloatingUI/useFloatingUI.tsx:52]: I think the choices are: lockScroll, preventScroll or disableScroll

Comment (tayyabataimur) [reply packages/core/src/utils/useFloatingUI/useFloatingUI.tsx:52]: `lockscroll` is consistent with Floating UI's terminology but will it be intuitive for our users, and be consistent in naming with other components in Salt?

**Review by Fercas123 — APPROVED** [review]
