### PR TITLE
Fix component doc lab badge and missing next / prev bottom navs

### LINKED ISSUE #2712: Website does not render lab component badge correctly
### Package name(s)

Website

### Package version(s)

N/A

### Description

See screenshot 

IMG_8094

### Steps to reproduce

Go to dropdown component page

https://www.saltdesignsystem.com/salt/components/dropdown/examples

### Expected behavior

/

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [X] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

### PR DESCRIPTION
**Pull request by origami-z**
- Stack "Lab Component" badge on mobile. To test, go to dropdown component page on mobile viewport.
- Add missing footer prev/next navigation links on component pages, so it's navigable on mobile.
- Use `replace` instead of `push` to redirect from `<Component>/index` to `<Component>/examples`, so that browser back button will not always circulate back to index.

closes #2712

### CODE REVIEW

File: site/src/mosaic-plugins/ChildrenDocPaginatorPlugin.mjs [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+
+    pageIndexToNavigation[page.route] = {
+      prev,
+      ...(next ? { next } : {}), // Don't want undefined or Mosaic will throw
+    };
+  }
+  return pageIndexToNavigation;
+}
+
+const ChildrenDocPaginatorPlugin = {
```
Comment (DavieReid) [inline site/src/mosaic-plugins/ChildrenDocPaginatorPlugin.mjs:38]: I guess you can make this name more specific as its a plugin for the salt site...

Comment (origami-z) [reply site/src/mosaic-plugins/ChildrenDocPaginatorPlugin.mjs]: Updated

File: site/src/mosaic-plugins/ChildrenDocPaginatorPlugin.mjs [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+  async $afterSource(pages) {
+    const componentRouteToName = buildRouteNavigationData(pages);
+
+    for (const page of pages) {
+      // Only work with components route
+      if (!new RegExp(`/components/`).test(page.route)) {
```
[the remark this answers is not in the document]
Comment (origami-z) [reply site/src/mosaic-plugins/ChildrenDocPaginatorPlugin.mjs]: Not sure it will save much. I will need to iterate everything twice anyway, once to get the order, once to add data to component pages only.

**Review by Fercas123 — APPROVED** [review]

**Review by DavieReid — APPROVED** [review]
