### PR TITLE
Add dark mode source support to image, fix themes page dark mode

### LINKED ISSUE #4907: Some site images don't work in dark mode
### Latest version

- [x] I have tested the latest version

### Description

Some images have transparent background so doesn't work in dark mode

### Steps to reproduce

https://www.saltdesignsystem.com/salt/themes/index#color-palette

### Expected behavior

_No response_

### Package name(s)

Core (@salt-ds/core)

### Package version(s)

_No response_

### Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [x] I am an employee of JPMorgan Chase & Co.

### PR DESCRIPTION
**Pull request by origami-z**
Check [`/salt/themes/index`](https://saltdesignsystem-git-4907-themes-page-dark-mode-fed-team.vercel.app/salt/themes/index) in both light and dark modes

Note: 
[Next.js doc](https://nextjs.org/docs/pages/api-reference/components/image#theme-detection-css) mentioned an approach with 2 `Image` using CSS to hide, but it will load 2 images regardless of modes. The best native HTML approach is by using [<picture>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture), however media query in <source> doesn't work with custom theme toggle

Figma [asset link](https://www.figma.com/design/auYJVYxgeu1SvY3jefe1qy/Salt-Next-Site-Assets?node-id=1181-10292&t=u4ibKD7lkBdCBR29-1)

Closes #4907

### CODE REVIEW

**Review by amritadesmet — APPROVED** [review]

File: site/src/components/mdx/image/Image.tsx [hunk 1]
```diff
@@ -9,14 +10,27 @@ export interface ImageProps extends Omit<NextImageProps, "src"> {
...
   ref,
 ) {
-  const resolvedSrc = useResolveRelativeUrl(src);
+  const siteMode = useColorMode();
+
+  const srcToUse = siteMode === "dark" && srcDark ? srcDark : src;
+
+  const resolvedSrc = useResolveRelativeUrl(srcToUse);
+
+  const resolvedSrcToUse =
```
Comment (mark-tate) [inline site/src/components/mdx/image/Image.tsx:29]: FYI: Did look at this
https://nextjs.org/docs/pages/api-reference/components/image#theme-detection-css
but really only of benefit when using 
`@media (prefers-color-scheme: dark) {`
Whilst we have an imperative  theme switcher, still good to know that NextImage has additional props/patterns of use.

**Review by mark-tate — APPROVED** [review]

File: site/src/components/mdx/image/Image.tsx (hunk 1 above)
Comment (origami-z) [reply site/src/components/mdx/image/Image.tsx:29]: Approach mentioned will load 2 images regardless of modes. The best native HTML approach is by using [`<picture>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture), however media query in `<source>` doesn't work with custom theme toggle

**Review by amritadesmet — APPROVED** [review]
